[package]
name = "akkurate-extension"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
akkurate-core = { path = "../core" }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["Window", "Storage"] }
console_error_panic_hook = { version = "0.1", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
wee_alloc = { version = "0.4", optional = true }
# reqwest is provided by akkurate-core

[features]
default = ["console_error_panic_hook"]
wee_alloc = ["dep:wee_alloc"]
